"""financial domain

Revision ID: 0001
Revises:
Create Date: 2026-09-04 08:18:44.802817
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code ~ '^[A-Z][A-Z0-9_]*$'", name=op.f("ck_categories_code_format")),
        sa.CheckConstraint("parent_id != id", name=op.f("ck_categories_not_own_parent")),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("code", name=op.f("uq_categories_code")),
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email = lower(btrim(email)) AND email ~ '^[^[:space:]@]+@[^[:space:]@]+$'",
            name=op.f("ck_users_email_canonical"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("institution_code", sa.String(length=100), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(
                "CHECKING",
                "SAVINGS",
                "CREDIT_CARD",
                "DEBIT_CARD",
                "CASH",
                "OTHER",
                name="account_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("account_number_masked", sa.String(length=8), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account_number_masked ~ '^\\*{4}[0-9]{4}$'",
            name=op.f("ck_accounts_masked_suffix_only"),
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_accounts_currency_format")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_accounts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("id", "user_id", name="uq_accounts_id_user"),
    )
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "merchant_aliases",
        sa.Column("pattern", sa.String(length=255), nullable=False),
        sa.Column("normalized_merchant", sa.String(length=255), nullable=False),
        sa.Column("default_category_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(pattern)) > 0", name=op.f("ck_merchant_aliases_pattern_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["default_category_id"],
            ["categories.id"],
            name=op.f("fk_merchant_aliases_default_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchant_aliases")),
        sa.UniqueConstraint("pattern", name=op.f("uq_merchant_aliases_pattern")),
    )
    op.create_index(
        op.f("ix_merchant_aliases_default_category_id"),
        "merchant_aliases",
        ["default_category_id"],
        unique=False,
    )
    op.create_table(
        "user_merchant_rules",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_key", sa.String(length=255), nullable=False),
        sa.Column("preferred_merchant_name", sa.String(length=255), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(merchant_key)) > 0",
            name=op.f("ck_user_merchant_rules_merchant_key_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_user_merchant_rules_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_merchant_rules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_merchant_rules")),
        sa.UniqueConstraint("user_id", "merchant_key", name="uq_user_merchant_rules_user_key"),
    )
    op.create_index(
        op.f("ix_user_merchant_rules_category_id"),
        "user_merchant_rules",
        ["category_id"],
        unique=False,
    )
    op.create_table(
        "import_batches",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "MANUAL_UPLOAD",
                "GMAIL",
                name="source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "file_format",
            sa.Enum(
                "PDF", "CSV", "XLSX", name="file_format", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("institution_code", sa.String(length=100), nullable=True),
        sa.Column("statement_type", sa.String(length=100), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("parser_name", sa.String(length=100), nullable=True),
        sa.Column("parser_version", sa.String(length=50), nullable=True),
        sa.Column("statement_period_start", sa.Date(), nullable=True),
        sa.Column("statement_period_end", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("reported_total", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("parsed_total", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("total_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("valid_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("duplicate_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("failed_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "validation_status",
            sa.Enum(
                "PASSED",
                "FAILED",
                "NOT_AVAILABLE",
                "NEEDS_REVIEW",
                name="validation_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="NOT_AVAILABLE",
            nullable=False,
        ),
        sa.Column(
            "import_status",
            sa.Enum(
                "PENDING",
                "PARSED",
                "AWAITING_CONFIRMATION",
                "COMPLETED",
                "FAILED",
                name="import_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_import_batches_currency_format")
        ),
        sa.CheckConstraint(
            "file_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_import_batches_sha256_format")
        ),
        sa.CheckConstraint(
            "parsed_total > '-Infinity'::numeric AND parsed_total < 'Infinity'::numeric",
            name=op.f("ck_import_batches_parsed_total_finite"),
        ),
        sa.CheckConstraint(
            "reported_total > '-Infinity'::numeric AND reported_total < 'Infinity'::numeric",
            name=op.f("ck_import_batches_reported_total_finite"),
        ),
        sa.CheckConstraint(
            "(reported_total IS NULL AND parsed_total IS NULL) OR currency IS NOT NULL",
            name=op.f("ck_import_batches_totals_require_currency"),
        ),
        sa.CheckConstraint(
            "statement_period_start <= statement_period_end",
            name=op.f("ck_import_batches_period_order"),
        ),
        sa.CheckConstraint(
            "total_rows >= 0 AND valid_rows >= 0 AND duplicate_rows >= 0 AND failed_rows >= 0",
            name=op.f("ck_import_batches_nonnegative_counters"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "user_id"],
            ["accounts.id", "accounts.user_id"],
            name="fk_import_batches_account_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_import_batches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
        sa.UniqueConstraint(
            "id", "account_id", "user_id", name="uq_import_batches_id_account_user"
        ),
    )
    op.create_index("ix_import_batches_account_id", "import_batches", ["account_id"], unique=False)
    op.create_index(
        "ix_import_batches_user_account_hash",
        "import_batches",
        ["user_id", "account_id", "file_hash"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("posted_date", sa.Date(), nullable=True),
        sa.Column("description_raw", sa.Text(), nullable=False),
        sa.Column("merchant_raw", sa.Text(), nullable=True),
        sa.Column("merchant_normalized", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "EXPENSE",
                "INCOME",
                "TRANSFER",
                "REFUND",
                "FEE",
                "INTEREST",
                "CARD_PAYMENT",
                "CASH_WITHDRAWAL",
                "UNKNOWN",
                name="transaction_type",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("balance_after", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("installment_index", sa.SmallInteger(), nullable=True),
        sa.Column("installment_count", sa.SmallInteger(), nullable=True),
        sa.Column("installment_plan_id", sa.Uuid(), nullable=True),
        sa.Column(
            "category_source",
            sa.Enum(
                "USER",
                "MERCHANT_RULE",
                "SYSTEM_RULE",
                "CLASSIFIER",
                "UNKNOWN",
                name="category_source",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column(
            "review_status",
            sa.Enum(
                "AUTO_CONFIRMED",
                "NEEDS_REVIEW",
                "USER_CONFIRMED",
                name="review_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="NEEDS_REVIEW",
            nullable=False,
        ),
        sa.Column("source_transaction_id", sa.Text(), nullable=True),
        sa.Column("source_row_number", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > '-Infinity'::numeric AND amount < 'Infinity'::numeric",
            name=op.f("ck_transactions_amount_finite"),
        ),
        sa.CheckConstraint(
            "balance_after > '-Infinity'::numeric AND balance_after < 'Infinity'::numeric",
            name=op.f("ck_transactions_balance_after_finite"),
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_transactions_currency_format")),
        sa.CheckConstraint(
            "installment_count > 0", name=op.f("ck_transactions_installment_count_positive")
        ),
        sa.CheckConstraint(
            "installment_index <= installment_count", name=op.f("ck_transactions_installment_order")
        ),
        sa.CheckConstraint(
            "installment_index > 0", name=op.f("ck_transactions_installment_index_positive")
        ),
        sa.CheckConstraint(
            "source_row_number > 0", name=op.f("ck_transactions_source_row_positive")
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "user_id"],
            ["accounts.id", "accounts.user_id"],
            name="fk_transactions_account_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_transactions_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id", "account_id", "user_id"],
            ["import_batches.id", "import_batches.account_id", "import_batches.user_id"],
            name="fk_transactions_import_account_owner",
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("id", "user_id", name="uq_transactions_id_user"),
    )
    op.create_index(
        "ix_transactions_account_date",
        "transactions",
        ["account_id", "transaction_date"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_account_source",
        "transactions",
        ["account_id", "source_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_category_id"), "transactions", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_import_batch_id"), "transactions", ["import_batch_id"], unique=False
    )
    op.create_index(
        "ix_transactions_user_date", "transactions", ["user_id", "transaction_date"], unique=False
    )
    op.create_index(
        "ix_transactions_user_merchant",
        "transactions",
        ["user_id", "merchant_normalized"],
        unique=False,
    )
    op.create_table(
        "transaction_links",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_transaction_id", sa.Uuid(), nullable=False),
        sa.Column("target_transaction_id", sa.Uuid(), nullable=False),
        sa.Column(
            "link_type",
            sa.Enum(
                "TRANSFER_PAIR",
                "CARD_PAYMENT_PAIR",
                "REFUND_OF",
                name="link_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "is_user_confirmed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("linked_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_transaction_links_currency_format")
        ),
        sa.CheckConstraint(
            "link_type = 'REFUND_OF' OR source_transaction_id < target_transaction_id",
            name=op.f("ck_transaction_links_symmetric_order"),
        ),
        sa.CheckConstraint(
            "linked_amount > '-Infinity'::numeric AND linked_amount < 'Infinity'::numeric",
            name=op.f("ck_transaction_links_linked_amount_finite"),
        ),
        sa.CheckConstraint(
            "(linked_amount IS NULL) = (currency IS NULL)",
            name=op.f("ck_transaction_links_amount_currency_pair"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_transaction_links_confidence_range"),
        ),
        sa.CheckConstraint(
            "linked_amount > 0", name=op.f("ck_transaction_links_linked_amount_positive")
        ),
        sa.CheckConstraint(
            "source_transaction_id != target_transaction_id",
            name=op.f("ck_transaction_links_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["source_transaction_id", "user_id"],
            ["transactions.id", "transactions.user_id"],
            name="fk_transaction_links_source_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_transaction_id", "user_id"],
            ["transactions.id", "transactions.user_id"],
            name="fk_transaction_links_target_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transaction_links_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_links")),
        sa.UniqueConstraint(
            "source_transaction_id",
            "target_transaction_id",
            "link_type",
            name="uq_transaction_links_pair_type",
        ),
    )
    op.create_index(
        op.f("ix_transaction_links_target_transaction_id"),
        "transaction_links",
        ["target_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_links_user_id"), "transaction_links", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_links_user_id"), table_name="transaction_links")
    op.drop_index(
        op.f("ix_transaction_links_target_transaction_id"), table_name="transaction_links"
    )
    op.drop_table("transaction_links")
    op.drop_index("ix_transactions_user_merchant", table_name="transactions")
    op.drop_index("ix_transactions_user_date", table_name="transactions")
    op.drop_index(op.f("ix_transactions_import_batch_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.drop_index("ix_transactions_account_source", table_name="transactions")
    op.drop_index("ix_transactions_account_date", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_import_batches_user_account_hash", table_name="import_batches")
    op.drop_index("ix_import_batches_account_id", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_user_merchant_rules_category_id"), table_name="user_merchant_rules")
    op.drop_table("user_merchant_rules")
    op.drop_index(op.f("ix_merchant_aliases_default_category_id"), table_name="merchant_aliases")
    op.drop_table("merchant_aliases")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
